Description: >
  Vacation_Spot
  This template defines the K8S cluster

Parameters:
  StackName:
    Type: String
    Description: Name of the Stack.

  ClusterName:
    Description: Name of the cluster.
    Type: String

Resources:
  ClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  KubernetesCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterName
      ResourcesVpcConfig:
        SecurityGroupIds:
        - Fn::ImportValue:
            !Sub "${StackName}-SecurityGroups"
        SubnetIds:
          Fn::Split:
            - ","
            - Fn::ImportValue:
                !Sub "${StackName}-Subnets"
      RoleArn: !GetAtt ClusterRole.Arn

Outputs:
  K8SCluster:
    Description: The K8S Cluster Name
    Value: !Ref KubernetesCluster
    Export:
      Name: !Sub "${StackName}-Cluster"